// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni

#pragma once

#include <functional>

/**
 * enum comment
 *
 * @deprecated Use something else
 */
enum class [[deprecated("Use something else")]] MyEnum : int {
    /** @deprecated Use something else */
    OPTION1 = 0,
    /** not deprecated */
    OPTION2 = 1,
};

namespace std {

template <>
struct hash<::MyEnum> {
    size_t operator()(::MyEnum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
