// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni

#pragma once

#include <cstdint>

/**
 * interface comment
 *
 * @deprecated Use someother interface
 */
class [[deprecated("Use someother interface")]] MyInterface {
public:
    virtual ~MyInterface() {}

    /** @deprecated Use someother constant */
    [[deprecated("Use someother constant")]]
    static constexpr int32_t VERSION = 1;

    /** @deprecated Use someother method */
    [[deprecated("Use someother method")]]
    virtual void method_a(int32_t value) = 0;

    /** @deprecated Use someother method */
    [[deprecated("Use someother method")]]
    virtual void method_b(int32_t value) const = 0;

    /** @deprecated Use someother method */
    [[deprecated("Use someother method")]]
    static void method_c(int32_t value);

    /** not deprecated */
    virtual void method_d() = 0;

    /** really im not */
    virtual void method_e() = 0;
};
