// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

/**
 * record comment
 *
 * @deprecated Use someother record
 */
struct [[deprecated("Use someother record")]] MyRecord final {

    /** @deprecated Use someother constant */
    [[deprecated("Use someother constant")]]
    static constexpr int32_t VERSION = 1;
    /** @deprecated Use someother attribute */
    [[deprecated("Use someother attribute")]]
    std::string attribute;
    /** not deprecated */
    std::string another;
    /** @deprecated Use someother attribute */
    [[deprecated("Use someother attribute")]]
    std::string again;

    MyRecord(std::string attribute_,
             std::string another_,
             std::string again_)
    : attribute(std::move(attribute_))
    , another(std::move(another_))
    , again(std::move(again_))
    {}
};
