// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni


/**
 * enum comment
 *
 * @deprecated Use something else
 */
export enum MyEnum {
    /** @deprecated Use something else */
    OPTION1 = 0,
    /** not deprecated */
    OPTION2 = 1,
}

/**
 * flags comment
 *
 * @deprecated Use someother flags
 */
export enum MyFlags {
    /** @deprecated Use someother flag */
    FLAG1 = 1 << 0,
    /** not deprecated */
    FLAG2 = 1 << 1,
}

/**
 * record comment
 *
 * @deprecated Use someother record
 */
export interface /*record*/ MyRecord {
    /** @deprecated Use someother attribute */
    attribute: string;
    /** not deprecated */
    another: string;
    /** @deprecated Use someother attribute */
    again: string;
}
export namespace MyRecord {
    /** @deprecated Use someother constant */
    export const VERSION = 1;
}

/**
 * interface comment
 *
 * @deprecated Use someother interface
 */
export interface MyInterface {
    /** @deprecated Use someother method */
    methodA(value: number): void;
    /** @deprecated Use someother method */
    methodB(value: number): void;
    /** not deprecated */
    methodD(): void;
    /** really im not */
    methodE(): void;
}
export namespace MyInterface {
    /** @deprecated Use someother constant */
    export const VERSION = 1;
}
export interface MyInterface_statics {
    /** @deprecated Use someother method */
    methodC(value: number): void;
}

export interface Module_statics {
    MyInterface: MyInterface_statics;
}
