# AUTOGENERATED FILE - DO NOT MODIFY!
# This file was generated by Djinni from all_datatypes.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyBinary, CPyBoxedBool, CPyDate, CPyObject, CPyObject, CPyObjectProxy, CPyPrimitive, CPyRecord, CPyString

from dh__list_bool import ListBoolHelper
from dh__map_int8_t_bool import MapInt8TBoolHelper
from dh__map_int8_t_bool import MapInt8TBoolProxy
from dh__set_bool import SetBoolHelper
from dh__set_bool import SetBoolProxy
from _cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class AllDatatypes:
    c_data_set = MultiSet()

    @staticmethod
    def check_c_data_set_empty():
        assert len(AllDatatypes.c_data_set) == 0
        ListBoolHelper.check_c_data_set_empty()
        SetBoolHelper.check_c_data_set_empty()
        MapInt8TBoolHelper.check_c_data_set_empty()


    def __init__(self, booleanData, integer8Data, integer16Data, integer32Data, integer64Data, float32Data, float64Data, stringData, binaryData, dateData, listData, setData, mapData, optionalData):
        self.booleanData = booleanData
        self.integer8Data = integer8Data
        self.integer16Data = integer16Data
        self.integer32Data = integer32Data
        self.integer64Data = integer64Data
        self.float32Data = float32Data
        self.float64Data = float64Data
        self.stringData = stringData
        self.binaryData = binaryData
        self.dateData = dateData
        self.listData = listData
        self.setData = setData
        self.mapData = mapData
        self.optionalData = optionalData

