// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni


/** enum comment */
export enum MyEnum {
    /** enum option comment */
    OPTION1,
    OPTION2,
    OPTION3,
}

export interface ns_testsuite {
}
export interface Module_statics {

    testsuite: ns_testsuite;
}
