// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni


/** enum comment */
export enum MyEnum {
    /** enum option comment */
    OPTION1 = 0,
    OPTION2 = 1,
    OPTION3 = 2,
}

export interface Module_statics {
}
