// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni


export enum EnumData {
    A,
    B,
}

export interface /*record*/ AllDatatypes {
    booleanData: boolean;
    integer8Data: number;
    integer16Data: number;
    integer32Data: number;
    integer64Data: bigint;
    float32Data: number;
    float64Data: number;
    stringData: string;
    binaryData: Uint8Array;
    dateData: Date;
    listData: Array<boolean>;
    setData: Set<boolean>;
    mapData: Map<number, boolean>;
    optionalData?: boolean;
    enumData: EnumData;
}

export interface ns_testsuite {
}
export interface Module_statics {

    testsuite: ns_testsuite;
}
