// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from all_datatypes.djinni

#pragma once

#include <chrono>
#include <cstdint>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

struct AllDatatypes final {
    bool booleanData;
    int8_t integer8Data;
    int16_t integer16Data;
    int32_t integer32Data;
    int64_t integer64Data;
    float float32Data;
    double float64Data;
    std::string stringData;
    std::vector<uint8_t> binaryData;
    std::chrono::system_clock::time_point dateData;
    std::vector<bool> listData;
    std::unordered_set<bool> setData;
    std::unordered_map<int8_t, bool> mapData;
    std::optional<bool> optionalData;

    AllDatatypes(bool booleanData_,
                 int8_t integer8Data_,
                 int16_t integer16Data_,
                 int32_t integer32Data_,
                 int64_t integer64Data_,
                 float float32Data_,
                 double float64Data_,
                 std::string stringData_,
                 std::vector<uint8_t> binaryData_,
                 std::chrono::system_clock::time_point dateData_,
                 std::vector<bool> listData_,
                 std::unordered_set<bool> setData_,
                 std::unordered_map<int8_t, bool> mapData_,
                 std::optional<bool> optionalData_)
    : booleanData(std::move(booleanData_))
    , integer8Data(std::move(integer8Data_))
    , integer16Data(std::move(integer16Data_))
    , integer32Data(std::move(integer32Data_))
    , integer64Data(std::move(integer64Data_))
    , float32Data(std::move(float32Data_))
    , float64Data(std::move(float64Data_))
    , stringData(std::move(stringData_))
    , binaryData(std::move(binaryData_))
    , dateData(std::move(dateData_))
    , listData(std::move(listData_))
    , setData(std::move(setData_))
    , mapData(std::move(mapData_))
    , optionalData(std::move(optionalData_))
    {}
};
