// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_enum.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, ITMyEnum)
{
    ITMyEnumOption1,
    ITMyEnumOption2,
    ITMyEnumOption3,
};
