// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

#include "my_record.hpp"  // my header

namespace djinni_generated {

auto MyRecord::toCpp(const JsType& j) -> CppType {
    return {::djinni::I32::Boxed::toCpp(j["id"]),
            ::djinni::String::Boxed::toCpp(j["info"]),
            ::djinni::Set<::djinni::String>::Boxed::toCpp(j["store"]),
            ::djinni::Map<::djinni::String, ::djinni::I32>::Boxed::toCpp(j["hash"])};
}
auto MyRecord::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("id", ::djinni::I32::Boxed::fromCpp(c.id));
    js.set("info", ::djinni::String::Boxed::fromCpp(c.info));
    js.set("store", ::djinni::Set<::djinni::String>::Boxed::fromCpp(c.store));
    js.set("hash", ::djinni::Map<::djinni::String, ::djinni::I32>::Boxed::fromCpp(c.hash));
    return js;
}

namespace {
    EM_JS(void, djinni_init__my_record_consts, (), {
        if (!('MyRecord' in Module)) {
            Module.MyRecord = {};
        }
        Module.MyRecord.STRING_CONST = "Constants can be put here";
    })
}
void MyRecord::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init__my_record_consts();
    });
}

EMSCRIPTEN_BINDINGS(_my_record_consts) {
    MyRecord::staticInitializeConstants();
}

}  // namespace djinni_generated
