// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

#pragma once

#include "../cpp-headers/my_record.hpp"
#include "djinni/wasm/djinni_wasm.hpp"

namespace djinni_generated {

struct MyRecord
{
    using CppType = ::MyRecord;
    using JsType = em::val;
    using Boxed = MyRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
