// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from requires.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "requires_all_interface.hpp"

namespace djinni_generated {

class RequiresAllInterface final : ::djinni::JniInterface<::RequiresAllInterface, RequiresAllInterface> {
public:
    using CppType = std::shared_ptr<::RequiresAllInterface>;
    using CppOptType = std::shared_ptr<::RequiresAllInterface>;
    using JniType = jobject;

    using Boxed = RequiresAllInterface;

    ~RequiresAllInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<RequiresAllInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<RequiresAllInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    RequiresAllInterface();
    friend ::djinni::JniClass<RequiresAllInterface>;
    friend ::djinni::JniInterface<::RequiresAllInterface, RequiresAllInterface>;

};

}  // namespace djinni_generated
