// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from requires.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "requires_interface.hpp"

namespace djinni_generated {

class RequiresInterface final : ::djinni::JniInterface<::RequiresInterface, RequiresInterface> {
public:
    using CppType = std::shared_ptr<::RequiresInterface>;
    using CppOptType = std::shared_ptr<::RequiresInterface>;
    using JniType = jobject;

    using Boxed = RequiresInterface;

    ~RequiresInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<RequiresInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<RequiresInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    RequiresInterface();
    friend ::djinni::JniClass<RequiresInterface>;
    friend ::djinni::JniInterface<::RequiresInterface, RequiresInterface>;

};

}  // namespace djinni_generated
