// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from requires.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "requires_eq_interface.hpp"

namespace djinni_generated {

class RequiresEqInterface final : ::djinni::JniInterface<::RequiresEqInterface, RequiresEqInterface> {
public:
    using CppType = std::shared_ptr<::RequiresEqInterface>;
    using CppOptType = std::shared_ptr<::RequiresEqInterface>;
    using JniType = jobject;

    using Boxed = RequiresEqInterface;

    ~RequiresEqInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<RequiresEqInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<RequiresEqInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    RequiresEqInterface();
    friend ::djinni::JniClass<RequiresEqInterface>;
    friend ::djinni::JniInterface<::RequiresEqInterface, RequiresEqInterface>;

};

}  // namespace djinni_generated
