# AUTOGENERATED FILE - DO NOT MODIFY!
# This file was generated by Djinni from my_enum.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

from enum import IntEnum, unique

@unique
class MyEnum(IntEnum):
    Option1 = 0
    Option2 = 1
    Option3 = 2
