// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_json_specialized_datatypes.djinni

#pragma once

#include "json+extension.hpp"
#include "my_enum.hpp"
#include <algorithm>
#include <nlohmann/json.hpp>

namespace nlohmann {

template<>
struct adl_serializer<::custom_namespace::MyEnum>
{
    static void to_json(json& j, ::custom_namespace::MyEnum e)
    {
        static const std::pair<::custom_namespace::MyEnum, json> m[] = {{::custom_namespace::MyEnum::FIRSTENUMVALUE,"FirstEnumValue"},{::custom_namespace::MyEnum::SECONDENUMVALUE,"SecondEnumValue"}};
        auto it = std::find_if(std::begin(m), std::end(m),
                               [e](const std::pair<::custom_namespace::MyEnum, json>& ej_pair) -> bool
        {
            return ej_pair.first == e;
        });
        j = ((it != std::end(m)) ? it : std::begin(m))->second;
    }
    static void from_json(const json& j, ::custom_namespace::MyEnum& e)
    {
        static const std::pair<::custom_namespace::MyEnum, json> m[] = {{::custom_namespace::MyEnum::FIRSTENUMVALUE,"FirstEnumValue"},{::custom_namespace::MyEnum::SECONDENUMVALUE,"SecondEnumValue"}};
        auto it = std::find_if(std::begin(m), std::end(m),
                               [j](const std::pair<::custom_namespace::MyEnum, json>& ej_pair) -> bool
        {
            return ej_pair.second == j;
        });
        e = ((it != std::end(m)) ? it : std::begin(m))->first;
    }
};

}  // namespace nlohmann
