// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_json_specialized_datatypes.djinni

#pragma once

#include "json+extension.hpp"
#include "my_enum+json.hpp"
#include "my_flags+json.hpp"
#include <nlohmann/json.hpp>

namespace custom_namespace {

inline void from_json(const nlohmann::json & j, my_record& result)  {
    if (j.contains("myEnum")) {
        j.at("myEnum").get_to(result.myEnum);
    }
    if (j.contains("myFlags")) {
        j.at("myFlags").get_to(result.myFlags);
    }
}
inline void to_json(nlohmann::json & j, const my_record & item)  {
    j = nlohmann::json {
        {"myEnum", item.myEnum},
        {"myFlags", item.myFlags}
    };
}

}  // namespace custom_namespace
