// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_json_specialized_datatypes.djinni

#pragma once

#include "json+extension.hpp"
#include "my_enum+json.hpp"
#include "my_flags+json.hpp"
#include <nlohmann/json.hpp>

namespace nlohmann {

template <>
struct adl_serializer<::custom_namespace::MyRecord>  {
    static ::custom_namespace::MyRecord from_json(const json & j)  {
        auto result = ::custom_namespace::MyRecord();
        if (j.contains("myEnum")) {
            j.at("myEnum").get_to(result.myEnum);
        }
        if (j.contains("myFlags")) {
            j.at("myFlags").get_to(result.myFlags);
        }
        return result;
    }
    static void to_json(json & j, const ::custom_namespace::MyRecord & item)  {
        j = json {
            {"myEnum", item.myEnum},
            {"myFlags", item.myFlags}
        };
    }
};

}  // namespace nlohmann
