// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_flags.djinni

#import <Foundation/Foundation.h>

typedef NS_OPTIONS(NSUInteger, ITMyFlags)
{
    ITMyFlagsNoFlags = 0,
    ITMyFlagsFlag1 = 1 << 0,
    ITMyFlagsFlag2 = 1 << 1,
    ITMyFlagsFlag3 = 1 << 2,
    ITMyFlagsAllFlags = 0 | ITMyFlagsFlag1 | ITMyFlagsFlag2 | ITMyFlagsFlag3,
};
