// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record_objc_generics.djinni

#import <Foundation/Foundation.h>

/** record comment */
@interface ITMyRecord : NSObject
- (nonnull instancetype)initWithNames:(nonnull NSArray *)names
                           typedNames:(nonnull NSArray<NSString *> *)typedNames;
+ (nonnull instancetype)myRecordWithNames:(nonnull NSArray *)names
                               typedNames:(nonnull NSArray<NSString *> *)typedNames;

@property (nonatomic, readonly, nonnull) NSArray * names;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * typedNames;

@end
