# AUTOGENERATED FILE - DO NOT MODIFY!
# This file was generated by Djinni from using_custom_datatypes.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyRecord, CPyString
from _cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class CustomDatatype:
    c_data_set = MultiSet()

    @staticmethod
    def check_c_data_set_empty():
        assert len(CustomDatatype.c_data_set) == 0


    def __init__(self, recordData):
        self.recordData = recordData

