# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from using_custom_datatypes.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyRecord

from custom_datatype import CustomDatatype
from custom_datatype_helper import CustomDatatypeHelper
from _cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class OtherRecord:
    c_data_set = MultiSet()

    @staticmethod
    def check_c_data_set_empty():
        assert len(OtherRecord.c_data_set) == 0
        CustomDatatype.check_c_data_set_empty()


    def __init__(self, customDatatypeData):
        self.customDatatypeData = customDatatypeData

