// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#include "all_datatypes.hpp"  // my header
#include "enum_data.hpp"

namespace djinni_generated {

auto AllDatatypes::toCpp(const JsType& j) -> CppType {
    return {::djinni::Bool::Boxed::toCpp(j["booleanData"]),
            ::djinni::I8::Boxed::toCpp(j["integer8Data"]),
            ::djinni::I16::Boxed::toCpp(j["integer16Data"]),
            ::djinni::I32::Boxed::toCpp(j["integer32Data"]),
            ::djinni::I64::Boxed::toCpp(j["integer64Data"]),
            ::djinni::F32::Boxed::toCpp(j["float32Data"]),
            ::djinni::F64::Boxed::toCpp(j["float64Data"]),
            ::djinni::String::Boxed::toCpp(j["stringData"]),
            ::djinni::Binary::Boxed::toCpp(j["binaryData"]),
            ::djinni::Date::Boxed::toCpp(j["dateData"]),
            ::djinni::List<::djinni::Bool>::Boxed::toCpp(j["listData"]),
            ::djinni::Set<::djinni::Bool>::Boxed::toCpp(j["setData"]),
            ::djinni::Map<::djinni::I8, ::djinni::Bool>::Boxed::toCpp(j["mapData"]),
            ::djinni::Optional<std::optional, ::djinni::Bool>::Boxed::toCpp(j["optionalData"]),
            ::djinni_generated::EnumData::Boxed::toCpp(j["enumData"])};
}
auto AllDatatypes::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("booleanData", ::djinni::Bool::Boxed::fromCpp(c.booleanData));
    js.set("integer8Data", ::djinni::I8::Boxed::fromCpp(c.integer8Data));
    js.set("integer16Data", ::djinni::I16::Boxed::fromCpp(c.integer16Data));
    js.set("integer32Data", ::djinni::I32::Boxed::fromCpp(c.integer32Data));
    js.set("integer64Data", ::djinni::I64::Boxed::fromCpp(c.integer64Data));
    js.set("float32Data", ::djinni::F32::Boxed::fromCpp(c.float32Data));
    js.set("float64Data", ::djinni::F64::Boxed::fromCpp(c.float64Data));
    js.set("stringData", ::djinni::String::Boxed::fromCpp(c.stringData));
    js.set("binaryData", ::djinni::Binary::Boxed::fromCpp(c.binaryData));
    js.set("dateData", ::djinni::Date::Boxed::fromCpp(c.dateData));
    js.set("listData", ::djinni::List<::djinni::Bool>::Boxed::fromCpp(c.listData));
    js.set("setData", ::djinni::Set<::djinni::Bool>::Boxed::fromCpp(c.setData));
    js.set("mapData", ::djinni::Map<::djinni::I8, ::djinni::Bool>::Boxed::fromCpp(c.mapData));
    js.set("optionalData", ::djinni::Optional<std::optional, ::djinni::Bool>::Boxed::fromCpp(c.optionalData));
    js.set("enumData", ::djinni_generated::EnumData::Boxed::fromCpp(c.enum_data));
    return js;
}

}  // namespace djinni_generated
