// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once

#include "../cpp-headers/all_datatypes.hpp"
#include "djinni/wasm/djinni_wasm.hpp"

namespace djinni_generated {

struct AllDatatypes
{
    using CppType = ::AllDatatypes;
    using JsType = em::val;
    using Boxed = AllDatatypes;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
