// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#include "enum_data.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init_testsuite_enum_data_consts, (), {
        Module.testsuite_EnumData =  {
            A : 0,
            B : 1,
        }
    })
}

void EnumData::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init_testsuite_enum_data_consts();
        ::djinni::djinni_register_name_in_ns("testsuite_EnumData", "testsuite.EnumData");
    });
}

EMSCRIPTEN_BINDINGS(testsuite_enum_data) {
    EnumData::staticInitializeConstants();
}

}  // namespace djinni_generated
