// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once

#include "../cpp-headers/enum_data.hpp"
#include "djinni/wasm/djinni_wasm.hpp"

namespace djinni_generated {

struct EnumData: ::djinni::WasmEnum<::EnumData> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
