// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "enum_data.hpp"

namespace djinni_generated {

struct EnumData: ::djinni::WasmEnum<::EnumData> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
