// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

struct DjinniOtherRecord;
void other_record___delete(struct DjinniRecordHandle * );
void optional_other_record___delete(struct DjinniOptionalRecordHandle * );
void other_record_add_callback_get_other_record_f1(struct DjinniRecordHandle *( * ptr)(struct DjinniRecordHandle *));
void other_record_add_callback_create_other_record(struct DjinniRecordHandle *( * ptr)(struct DjinniRecordHandle *));
void other_record_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
