// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

struct DjinniCustomDatatype;
void custom_datatype___delete(struct DjinniRecordHandle * );
void optional_custom_datatype___delete(struct DjinniOptionalRecordHandle * );
void custom_datatype_add_callback_get_custom_datatype_f1(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void custom_datatype_add_callback_create_custom_datatype(struct DjinniRecordHandle *( * ptr)(struct DjinniString *));
void custom_datatype_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
