// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extern_generics.djinni

#pragma once

#include "../cpp-headers/my_record.hpp"
#include "djinni/cppcli/Marshal.hpp"

/** record comment */
[System::Serializable]
public ref class MyRecord : System::IEquatable<MyRecord^> {
public:

    property System::Collections::Generic::List<System::String^>^ Builtin
    {
        System::Collections::Generic::List<System::String^>^ get();
    }

    property System::Collections::Generic::List<System::String^>^ External
    {
        System::Collections::Generic::List<System::String^>^ get();
    }

    property System::Collections::Generic::List<System::String^>^ OptionalBuiltin
    {
        System::Collections::Generic::List<System::String^>^ get();
    }

    property System::Collections::Generic::List<System::String^>^ OptionalExternal
    {
        System::Collections::Generic::List<System::String^>^ get();
    }

    property System::Collections::Generic::List<System::Collections::Generic::List<System::String^>^>^ ListOfList
    {
        System::Collections::Generic::List<System::Collections::Generic::List<System::String^>^>^ get();
    }

    property System::Collections::Generic::List<System::Collections::Generic::List<System::String^>^>^ ListOfExternal
    {
        System::Collections::Generic::List<System::Collections::Generic::List<System::String^>^>^ get();
    }

    MyRecord(System::Collections::Generic::List<System::String^>^ builtin,
             System::Collections::Generic::List<System::String^>^ external,
             System::Collections::Generic::List<System::String^>^ optionalBuiltin,
             System::Collections::Generic::List<System::String^>^ optionalExternal,
             System::Collections::Generic::List<System::Collections::Generic::List<System::String^>^>^ listOfList,
             System::Collections::Generic::List<System::Collections::Generic::List<System::String^>^>^ listOfExternal);

    System::String^ ToString() override;

    virtual bool Equals(MyRecord^ other);
    bool Equals(System::Object^ obj) override;
    int GetHashCode() override;

internal:
    using CppType = ::MyRecord;
    using CsType = MyRecord^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);

private:
    System::Collections::Generic::List<System::String^>^ _builtin;
    System::Collections::Generic::List<System::String^>^ _external;
    System::Collections::Generic::List<System::String^>^ _optionalBuiltin;
    System::Collections::Generic::List<System::String^>^ _optionalExternal;
    System::Collections::Generic::List<System::Collections::Generic::List<System::String^>^>^ _listOfList;
    System::Collections::Generic::List<System::Collections::Generic::List<System::String^>^>^ _listOfExternal;
};
