// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extern_generics.djinni

#include "MyRecord.hpp"  // my header
#include "djinni/cppcli/Marshal.hpp"
#include <memory>

MyRecord::MyRecord(System::Collections::Generic::List<System::String^>^ builtin,
                   System::Collections::Generic::List<System::String^>^ external)
: _builtin(builtin)
, _external(external)
{}

System::Collections::Generic::List<System::String^>^ MyRecord::Builtin::get()
{
    return _builtin;
}

System::Collections::Generic::List<System::String^>^ MyRecord::External::get()
{
    return _external;
}

System::String^ MyRecord::ToString()
{
    return System::String::Format("MyRecord {{Builtin{0}, External{1}}}",
                                  Builtin,
                                  External);
}

bool MyRecord::Equals(MyRecord^ other) {
    if (ReferenceEquals(nullptr, other)) return false;
    if (ReferenceEquals(this, other)) return true;
    return Builtin->Equals(other->Builtin) && External->Equals(other->External);
}

bool MyRecord::Equals(System::Object^ obj) {
    if (ReferenceEquals(nullptr, obj)) return false;
    if (ReferenceEquals(this, obj)) return true;
    return obj->GetType() == GetType() && Equals((MyRecord^) obj);
}

int MyRecord::GetHashCode() {
    auto hashCode = Builtin->GetHashCode();
    hashCode = (hashCode * 397) ^ External->GetHashCode();
    return hashCode;
}

MyRecord::CppType MyRecord::ToCpp(MyRecord::CsType cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::List<::djinni::String>::ToCpp(cs->Builtin),
            ::djinni::List<::djinni::String>::ToCpp(cs->External)};
}

MyRecord::CsType MyRecord::FromCpp(const MyRecord::CppType& cpp)
{
    return gcnew MyRecord(::djinni::List<::djinni::String>::FromCpp(cpp.builtin),
                          ::djinni::List<::djinni::String>::FromCpp(cpp.external));
}
