// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extern_generics.djinni

#import "ITMyRecord.h"


@implementation ITMyRecord

- (nonnull instancetype)initWithBuiltin:(nonnull NSArray<NSString *> *)builtin
                               external:(nonnull NSArray<NSString *> *)external
{
    if (self = [super init]) {
        _builtin = [builtin copy];
        _external = external;
    }
    return self;
}

+ (nonnull instancetype)myRecordWithBuiltin:(nonnull NSArray<NSString *> *)builtin
                                   external:(nonnull NSArray<NSString *> *)external
{
    return [(ITMyRecord*)[self alloc] initWithBuiltin:builtin
                                             external:external];
}

- (BOOL)isEqual:(id)other
{
    if (![other isKindOfClass:[ITMyRecord class]]) {
        return NO;
    }
    ITMyRecord *typedOther = (ITMyRecord *)other;
    return [self.builtin isEqualToArray:typedOther.builtin] &&
            [self.external isEqual:typedOther.external];
}

- (NSUInteger)hash
{
    return NSStringFromClass([self class]).hash ^
            self.builtin.hash ^
            (self.external.hash);
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p builtin:%@ external:%@>", self.class, (void *)self, self.builtin, self.external];
}

@end
