// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#include "CustomDatatype.hpp"  // my header
#include "Marshal.hpp"
#include <memory>

CustomDatatype::CustomDatatype(System::String^ recordData)
: _recordData(recordData)
{}

System::String^ CustomDatatype::RecordData::get()
{
    return _recordData;
}

System::String^ CustomDatatype::ToString()
{
    return System::String::Format("CustomDatatype {{RecordData{0}}}",
                                  RecordData);
}

CustomDatatype::CppType CustomDatatype::ToCpp(CustomDatatype::CsType cs)
{
    ASSERT(cs != nullptr);
    return {::djinni::String::ToCpp(cs->RecordData)};
}

CustomDatatype::CsType CustomDatatype::FromCpp(const CustomDatatype::CppType& cpp)
{
    return gcnew CustomDatatype(::djinni::String::FromCpp(cpp.recordData));
}
