// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni

#pragma once

#include "../cpp-headers/custom_datatype.hpp"

[System::Serializable]
public ref class CustomDatatype {
public:

    property System::String^ RecordData
    {
        System::String^ get();
    }

    CustomDatatype(System::String^ recordData);

    System::String^ ToString() override;

internal:
    using CppType = ::CustomDatatype;
    using CsType = CustomDatatype^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);

private:
    System::String^ _recordData;
};
