// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni


export interface /*record*/ CustomDatatype {
    recordData: string;
}

export interface /*record*/ OtherRecord {
    customDatatypeData: CustomDatatype;
}

export interface Module_statics {
}
