// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

#pragma once

#include <atomic>
#include <optional>
#include "../cpp-headers/my_record.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "../cwrapper-headers/dh__map_string_int32_t.h"

#ifdef __cplusplus
}
#endif
struct DjinniMapStringInt32T {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::unordered_map<std::string, int32_t> & dc);
    static std::unordered_map<std::string, int32_t> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::optional<std::unordered_map<std::string, int32_t>> dc);
    static std::optional<std::unordered_map<std::string, int32_t>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
