// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

#import <Foundation/Foundation.h>

/** enum comment */
typedef NS_ENUM(NSInteger, ITMyEnum)
{
    /** enum option comment */
    ITMyEnumOption1 = 0,
    ITMyEnumOption2 = 1,
    ITMyEnumOption3 = 2,
};
