// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

#import <Foundation/Foundation.h>

/** enum comment */
typedef NS_ENUM(NSInteger, ITMyEnum)
{
    /** enum option comment */
    ITMyEnumOption1,
    ITMyEnumOption2,
    ITMyEnumOption3,
};
