# AUTOGENERATED FILE - DO NOT MODIFY!
# This file was generated by Djinni from my_flags.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

from enum import IntFlag

class MyFlags(IntFlag):
    No_Flags = 0
    Flag1 = 1
    Flag2 = 2
    Flag3 = 4
    All_Flags = 7
