// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from cpp_dependent_interface.djinni

#pragma once

#include "interface_dependency.hpp"
#include <memory>
#include <optional>

class DependentInterface {
public:
    virtual ~DependentInterface() {}

    virtual void method_taking_interface_dependency(const dropbox::oxygen::nn_shared_ptr<::InterfaceDependency> & dep) = 0;

    virtual void method_taking_optional_interface_dependency(const std::shared_ptr<::InterfaceDependency> & dep) = 0;

    virtual dropbox::oxygen::nn_shared_ptr<::InterfaceDependency> method_returning_interface_dependency() = 0;

    virtual std::shared_ptr<::InterfaceDependency> method_returning_optional_interface_dependency() = 0;
};
