// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

#pragma once

#include "../cpp-headers/my_record.hpp"
#include "MyEnum.hpp"

/** record comment */
[System::Serializable]
public ref class MyRecord {
public:

    static initonly System::String^ StringConst;

    static MyRecord() {
        StringConst = "Constants can be put here";
    }

    property int Id
    {
        int get();
    }

    property System::String^ Info
    {
        System::String^ get();
    }

    property System::Collections::Generic::HashSet<System::String^>^ Store
    {
        System::Collections::Generic::HashSet<System::String^>^ get();
    }

    property System::Collections::Generic::Dictionary<System::String^, int>^ Hash
    {
        System::Collections::Generic::Dictionary<System::String^, int>^ get();
    }

    property ::MyEnum MyEnum
    {
        ::MyEnum get();
    }

    MyRecord(int id,
             System::String^ info,
             System::Collections::Generic::HashSet<System::String^>^ store,
             System::Collections::Generic::Dictionary<System::String^, int>^ hash,
             ::MyEnum myEnum);

    System::String^ ToString() override;

internal:
    using CppType = ::MyRecord;
    using CsType = MyRecord^;

    static CppType ToCpp(CsType cs);
    static CsType FromCpp(const CppType& cpp);

private:
    /** record property comment */
    int _id;
    System::String^ _info;
    System::Collections::Generic::HashSet<System::String^>^ _store;
    System::Collections::Generic::Dictionary<System::String^, int>^ _hash;
    ::MyEnum _myEnum;
};
