// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_client_interface.djinni

#import <Foundation/Foundation.h>


@protocol ITMyClientInterface

- (BOOL)logString:(nonnull NSString *)str;

@end
