// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_client_interface.djinni

#import <Foundation/Foundation.h>


@protocol ITMyClientInterface <NSObject>

- (BOOL)logString:(nonnull NSString *)str;

@end
