// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extern_generics.djinni

#import "ITMyRecord+Private.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "djinni/objc/DJMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto MyRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::List<::djinni::String>::toCpp(obj.builtin),
            ::djinni::List<::djinni::String>::toCpp(obj.external)};
}

auto MyRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[::ITMyRecord alloc] initWithBuiltin:(::djinni::List<::djinni::String>::fromCpp(cpp.builtin))
                                        external:(::djinni::List<::djinni::String>::fromCpp(cpp.external))];
}

}  // namespace djinni_generated
