// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_flags.djinni

#include "my_flags.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init__my_flags_consts, (), {
        Module.MyFlags =  {
            NO_FLAGS : 0,
            /** flag option comment */
            FLAG1 : 1 << 0,
            FLAG2 : 1 << 1,
            FLAG3 : 1 << 2,
            ALL_FLAGS : 0 | (1 << 0) | (1 << 1) | (1 << 2),
        }
    })
}

void MyFlags::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init__my_flags_consts();
    });
}

EMSCRIPTEN_BINDINGS(_my_flags) {
    MyFlags::staticInitializeConstants();
}

}  // namespace djinni_generated
