// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_flags.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "my_flags.hpp"

namespace djinni_generated {

struct MyFlags: ::djinni::WasmEnum<::MyFlags> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
