// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_flags.djinni

#pragma once

#include "../cpp-headers/my_flags.hpp"
#include "djinni/wasm/djinni_wasm.hpp"

namespace djinni_generated {

struct MyFlags: ::djinni::WasmEnum<::MyFlags> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
