// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

#pragma once

#include "../cpp-headers/my_enum.hpp"

/** enum comment */
public enum class MyEnum {
    /** enum option comment */
    Option1 = 0,
    Option2 = 1,
    Option3 = 2,
};
