// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_enum.djinni

#pragma once

#include "my_enum.hpp"

public enum class MyEnum {
    Option1,
    Option2,
    Option3,
};
