// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_enum.djinni

#include "MyEnum.hpp"  // my header
#include "my_enum.hpp"

// Empty... making sure the symbols get included in the build.
