// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

#pragma once

#include "../cpp-headers/my_enum.hpp"

public enum class MyEnum {
    Option1,
    Option2,
    Option3,
};
