// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_record.djinni

#include "my_record.hpp"  // my header

std::string const MyRecord::STRING_CONST = {"Constants can be put here"};
