// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_client_interface.djinni


export interface MyClientInterface {
    logString(str: string): boolean;
}

export interface Module_statics {
}
