// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

#pragma once

#include "my_enum.hpp"
#include <cstdint>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>

/** record comment */
struct MyRecord final {

    static std::string const STRING_CONST;
    /** record property comment */
    int32_t id;
    std::string info;
    std::unordered_set<std::string> store;
    std::unordered_map<std::string, int32_t> hash;
    MyEnum my_enum;

    MyRecord(int32_t id_,
             std::string info_,
             std::unordered_set<std::string> store_,
             std::unordered_map<std::string, int32_t> hash_,
             MyEnum my_enum_)
    : id(std::move(id_))
    , info(std::move(info_))
    , store(std::move(store_))
    , hash(std::move(hash_))
    , my_enum(std::move(my_enum_))
    {}

    MyRecord()
    : id()
    , info()
    , store()
    , hash()
    , my_enum()
    {}
};
