// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes_json.djinni

#pragma once

#include "enum_data.hpp"
#include "json+extension.hpp"
#include <algorithm>
#include <nlohmann/json.hpp>

inline void to_json(nlohmann::json& j, enum_data e)
{
    static const std::pair<enum_data, nlohmann::json> m[] = {{enum_data::FIRSTENUMVALUE,"FirstEnumValue"},{enum_data::SECONDENUMVALUE,"SecondEnumValue"}};
    auto it = std::find_if(std::begin(m), std::end(m),
                           [e](const std::pair<enum_data, nlohmann::json>& ej_pair) -> bool
    {
        return ej_pair.first == e;
    });
    j = ((it != std::end(m)) ? it : std::begin(m))->second;
}
inline void from_json(const nlohmann::json& j, enum_data& e)
{
    static const std::pair<enum_data, nlohmann::json> m[] = {{enum_data::FIRSTENUMVALUE,"FirstEnumValue"},{enum_data::SECONDENUMVALUE,"SecondEnumValue"}};
    auto it = std::find_if(std::begin(m), std::end(m),
                           [j](const std::pair<enum_data, nlohmann::json>& ej_pair) -> bool
    {
        return ej_pair.second == j;
    });
    e = ((it != std::end(m)) ? it : std::begin(m))->first;
}
