// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes_json.djinni

#pragma once

#include <functional>

enum class EnumData : int {
    FIRSTENUMVALUE = 0,
    SECONDENUMVALUE = 1,
};

namespace std {

template <>
struct hash<::EnumData> {
    size_t operator()(::EnumData type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
