// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes_json.djinni

#pragma once

#include "enum_data.hpp"
#include "json+extension.hpp"
#include <algorithm>
#include <nlohmann/json.hpp>

namespace nlohmann {

template<>
struct adl_serializer<::EnumData>
{
    static void to_json(json& j, ::EnumData e)
    {
        static const std::pair<::EnumData, json> m[] = {{::EnumData::FIRSTENUMVALUE,"FirstEnumValue"},{::EnumData::SECONDENUMVALUE,"SecondEnumValue"}};
        auto it = std::find_if(std::begin(m), std::end(m),
                               [e](const std::pair<::EnumData, json>& ej_pair) -> bool
        {
            return ej_pair.first == e;
        });
        j = ((it != std::end(m)) ? it : std::begin(m))->second;
    }
    static void from_json(const json& j, ::EnumData& e)
    {
        static const std::pair<::EnumData, json> m[] = {{::EnumData::FIRSTENUMVALUE,"FirstEnumValue"},{::EnumData::SECONDENUMVALUE,"SecondEnumValue"}};
        auto it = std::find_if(std::begin(m), std::end(m),
                               [j](const std::pair<::EnumData, json>& ej_pair) -> bool
        {
            return ej_pair.second == j;
        });
        e = ((it != std::end(m)) ? it : std::begin(m))->first;
    }
};

}  // namespace nlohmann
