// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from cpp_intefaces_as_lambdas.djinni

#pragma once

#include <functional>

class LambdaConvertibleCallback {
public:
    virtual ~LambdaConvertibleCallback() {}

    virtual void callback_method(bool success) = 0;
};

class LambdaConvertibleCallbackLambdaAdapter : public LambdaConvertibleCallback
{
public:
    LambdaConvertibleCallbackLambdaAdapter(std::function<void(bool)> callback_)
    : callback(std::move(callback_))
    {
    }
    void callback_method(bool success) override
    {
        callback(success);
    }
private:
    std::function<void(bool)> callback;
};
