// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "my_enum.hpp"

namespace djinni_generated {

struct MyEnum: ::djinni::WasmEnum<::MyEnum> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
