// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

#pragma once

#include "../cpp-headers/my_enum.hpp"
#include "djinni/wasm/djinni_wasm.hpp"

namespace djinni_generated {

struct MyEnum: ::djinni::WasmEnum<::MyEnum> {
    static void staticInitializeConstants();
};

}  // namespace djinni_generated
