// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

#include "my_enum.hpp"  // my header
#include <mutex>

namespace djinni_generated {

namespace {
    EM_JS(void, djinni_init__my_enum_consts, (), {
        Module.MyEnum =  {
            /** enum option comment */
            OPTION1 : 0,
            OPTION2 : 1,
            OPTION3 : 2,
        }
    })
}

void MyEnum::staticInitializeConstants() {
    static std::once_flag initOnce;
    std::call_once(initOnce, [] {
        djinni_init__my_enum_consts();
    });
}

EMSCRIPTEN_BINDINGS(_my_enum) {
    MyEnum::staticInitializeConstants();
}

}  // namespace djinni_generated
