// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_cpp_interface.djinni

#pragma once

#include <cstdint>
#include <string>

class MyCppInterface {
public:
    virtual ~MyCppInterface() {}

    /** Interfaces can also have constants */
    static constexpr int32_t VERSION = 1;

    virtual void method_returning_nothing(int32_t value) = 0;

    virtual int32_t method_returning_some_type(const std::string & key) = 0;

    static int32_t get_version();
};
