// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni


/** record comment */
export interface /*record*/ MyRecord {
    /** record property comment */
    id: number;
    info: string;
    store: Set<string>;
    hash: Map<string, number>;
}
export namespace MyRecord {
    export const STRING_CONST = "Constants can be put here";
}

export interface Module_statics {
}
