// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from non_blocking_finalizers.djinni

package djinni.it;

import java.util.concurrent.LinkedBlockingQueue;

/**
 * Destroys Djinni {@code CppProxy} objects on a dedicated daemon thread instead of the
 * GC finalizer thread.
 *
 * <p>A proxy's {@code nativeDestroy} can block on long-held native locks. Android's
 * {@code FinalizerWatchdogDaemon} kills the process when a single {@code finalize()}
 * exceeds its deadline (10 s by default), and a blocked finalizer thread also stalls
 * every other pending finalization. Generated {@code finalize()} implementations
 * therefore hand destruction to this queue; its thread has no watchdog and may block
 * safely.
 *
 * <p>Enqueueing {@code this::_djinni_private_destroy} from {@code finalize()}
 * deliberately resurrects the proxy until the queue has destroyed it — legal per the
 * JLS (an object's finalizer runs at most once) and required: the native reference
 * must stay valid until {@code nativeDestroy} has run.
 */
public final class DjinniNativeDestructionQueue
{
    private static final LinkedBlockingQueue<Runnable> QUEUE = new LinkedBlockingQueue<>();

    static
    {
        Thread thread = new Thread(DjinniNativeDestructionQueue::drainLoop, "djinni-native-destroy");
        thread.setDaemon(true);
        thread.start();
    }

    private DjinniNativeDestructionQueue()
    {
    }

    /** Schedules a proxy destruction. Never blocks; safe to call from {@code finalize()}. */
    public static void enqueue(Runnable destroyNativeProxy)
    {
        // LinkedBlockingQueue is unbounded — offer never fails.
        QUEUE.offer(destroyNativeProxy);
    }

    private static void drainLoop()
    {
        while (true)
        {
            try
            {
                // May block on native locks for the duration of an in-flight operation —
                // deliberate: this thread has no watchdog deadline.
                QUEUE.take().run();
            }
            catch (InterruptedException e)
            {
                return; // Daemon thread — only interrupted at process death.
            }
            catch (Throwable t)
            {
                // Never let one failed destruction kill the queue; the proxy's destroyed
                // flag stays unset and nothing worse than a leak can follow.
            }
        }
    }
}
