// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from non_blocking_finalizers.djinni

package djinni.it;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class NonBlockingFinalizersInterface {
    public abstract void methodReturningNothing(int value);

    private static final class CppProxy extends NonBlockingFinalizersInterface
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        @SuppressWarnings("deprecation")
        protected void finalize() throws java.lang.Throwable
        {
            // nativeDestroy can block on long-held native locks; never block the
            // finalizer thread (watchdog-killed on Android). Enqueueing resurrects
            // this proxy until the queue destroys it on its own thread.
            DjinniNativeDestructionQueue.enqueue(this::_djinni_private_destroy);
            super.finalize();
        }

        @Override
        public void methodReturningNothing(int value)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_methodReturningNothing(this.nativeRef, value);
        }
        private native void native_methodReturningNothing(long _nativeRef, int value);
    }
}
