// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#import "ITCustomDatatype+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto CustomDatatype::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.recordData)};
}

auto CustomDatatype::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ITCustomDatatype alloc] initWithRecordData:(::djinni::String::fromCpp(cpp.recordData))];
}

}  // namespace djinni_generated
