// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#import "ITOtherRecord.h"
#include "other_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ITOtherRecord;

namespace djinni_generated {

struct OtherRecord
{
    using CppType = ::OtherRecord;
    using ObjcType = ITOtherRecord*;

    using Boxed = OtherRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
