// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#import "ITOtherRecord+Private.h"
#import "ITCustomDatatype+Private.h"
#include <cassert>

namespace djinni_generated {

auto OtherRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni_generated::CustomDatatype::toCpp(obj.customDatatypeData)};
}

auto OtherRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ITOtherRecord alloc] initWithCustomDatatypeData:(::djinni_generated::CustomDatatype::fromCpp(cpp.customDatatypeData))];
}

}  // namespace djinni_generated
