// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni

#pragma once

#include <string>
#include <utility>

struct CustomDatatype final {
    std::string recordData;

    CustomDatatype(std::string recordData_)
    : recordData(std::move(recordData_))
    {}

    CustomDatatype()
    : recordData()
    {}
};
