// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_flags.djinni

#pragma once

#include <atomic>
#include <optional>
#include "my_flags.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__my_flags.h"

#ifdef __cplusplus
}
#endif
int32_t int32_from_enum_my_flags(std::optional<::MyFlags> e);
int32_t int32_from_enum_my_flags(::MyFlags e);
std::optional<::MyFlags> get_boxed_enum_my_flags_from_int32(int32_t e);
