// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_record.djinni

#import <Foundation/Foundation.h>

@interface ITMyRecord : NSObject
- (nonnull instancetype)initWithId:(int32_t)id
                              info:(nonnull NSString *)info
                             store:(nonnull NSSet<NSString *> *)store
                              hash:(nonnull NSDictionary<NSString *, NSNumber *> *)hash;
+ (nonnull instancetype)myRecordWithId:(int32_t)id
                                  info:(nonnull NSString *)info
                                 store:(nonnull NSSet<NSString *> *)store
                                  hash:(nonnull NSDictionary<NSString *, NSNumber *> *)hash;

@property (nonatomic, readonly) int32_t id;

@property (nonatomic, readonly, nonnull) NSString * info;

@property (nonatomic, readonly, nonnull) NSSet<NSString *> * store;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSNumber *> * hash;

@end

extern NSString * __nonnull const ITMyRecordStringConst;
