// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

#import "ITMyEnum.h"
#import <Foundation/Foundation.h>

/** record comment */
@interface ITMyRecord : NSObject
- (nonnull instancetype)initWithId:(int32_t)id
                              info:(nonnull NSString *)info
                             store:(nonnull NSSet<NSString *> *)store
                              hash:(nonnull NSDictionary<NSString *, NSNumber *> *)hash
                            myEnum:(ITMyEnum)myEnum;
+ (nonnull instancetype)myRecordWithId:(int32_t)id
                                  info:(nonnull NSString *)info
                                 store:(nonnull NSSet<NSString *> *)store
                                  hash:(nonnull NSDictionary<NSString *, NSNumber *> *)hash
                                myEnum:(ITMyEnum)myEnum;

/** record property comment */
@property (nonatomic, readonly) int32_t id;

@property (nonatomic, readonly, nonnull) NSString * info;

@property (nonatomic, readonly, nonnull) NSSet<NSString *> * store;

@property (nonatomic, readonly, nonnull) NSDictionary<NSString *, NSNumber *> * hash;

@property (nonatomic, readonly) ITMyEnum myEnum;

@end

extern NSString * __nonnull const ITMyRecordStringConst;
