// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record_default_ctor.djinni

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>

struct MyRecordDefaultCtor final {
    int32_t id;
    std::string info;
    std::unordered_set<std::string> store;
    std::unordered_map<std::string, int32_t> hash;

    MyRecordDefaultCtor(int32_t id_,
                        std::string info_,
                        std::unordered_set<std::string> store_,
                        std::unordered_map<std::string, int32_t> hash_)
    : id(std::move(id_))
    , info(std::move(info_))
    , store(std::move(store_))
    , hash(std::move(hash_))
    {}

    MyRecordDefaultCtor() = default;
};
