// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#pragma once

#include "custom_datatype.hpp"
#include <utility>

struct OtherRecord final {
    CustomDatatype customDatatypeData;

    OtherRecord(CustomDatatype customDatatypeData_)
    : customDatatypeData(std::move(customDatatypeData_))
    {}
};
