// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#include "EnumData.hpp"  // my header
#include "../cpp-headers/enum_data.hpp"

// Empty... making sure the symbols get included in the build.
