// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once

#include "../cpp-headers/enum_data.hpp"

public enum class EnumData {
    A,
    B,
};
