// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni

#import <Foundation/Foundation.h>

/**
 * enum comment
 *
 * @deprecated Use something else
 */
 __deprecated_msg("Use something else")
typedef NS_ENUM(NSInteger, ITMyEnum)
{
    /** @deprecated Use something else */
    ITMyEnumOption1 = 0,
    /** not deprecated */
    ITMyEnumOption2 = 1,
};
