// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni

#import <Foundation/Foundation.h>

/**
 * flags comment
 *
 * @deprecated Use someother flags
 */
 __deprecated_msg("Use someother flags")
typedef NS_OPTIONS(NSUInteger, ITMyFlags)
{
    /** @deprecated Use someother flag */
    ITMyFlagsFlag1 = 1u << 0,
    /** not deprecated */
    ITMyFlagsFlag2 = 1u << 1,
};
