// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdint.h> // python_cdef_ignore

void map_string_int32_t___delete(struct DjinniObjectHandle *);
void optional_map_string_int32_t___delete(struct DjinniOptionalObjectHandle *);
void map_string_int32_t_add_callback___delete(void(* ptr)(struct DjinniObjectHandle * ));
void map_string_int32_t_add_callback__get_value(int32_t( * ptr)(struct DjinniObjectHandle *, struct DjinniString *));
void map_string_int32_t_add_callback__get_size(size_t( * ptr)(struct DjinniObjectHandle *));
void map_string_int32_t_add_callback__create(struct DjinniObjectHandle *( * ptr)(void));
void map_string_int32_t_add_callback__add(void( * ptr)(struct DjinniObjectHandle *, struct DjinniString *, int32_t));
void map_string_int32_t_add_callback__next(struct DjinniString *( * ptr)(struct DjinniObjectHandle *));
