// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdint.h> // python_cdef_ignore

void set_string___delete(struct DjinniObjectHandle *);
void optional_set_string___delete(struct DjinniOptionalObjectHandle *);
void set_string_add_callback___delete(void(* ptr)(struct DjinniObjectHandle * ));
void set_string_add_callback__get_size(size_t( * ptr)(struct DjinniObjectHandle *));
void set_string_add_callback__create(struct DjinniObjectHandle *( * ptr)(void));
void set_string_add_callback__add(void( * ptr)(struct DjinniObjectHandle *, struct DjinniString *));
void set_string_add_callback__next(struct DjinniString *( * ptr)(struct DjinniObjectHandle *));
