// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_cpp_interface.djinni


/** interface comment */
export interface MyCppInterface {
    /** method comment */
    methodReturningNothing(value: number): void;
    methodReturningSomeType(key: string): number;
    methodChangingNothing(): number;
}
export namespace MyCppInterface {
    /** Interfaces can also have constants */
    export const VERSION = 1;
}
export interface MyCppInterface_statics {
    getVersion(): number;
}

export interface Module_statics {
    MyCppInterface: MyCppInterface_statics;
}
