// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_flags.djinni

#pragma once

#include "djinni_support.hpp"
#include "my_flags.hpp"

namespace djinni_generated {

class MyFlags final : ::djinni::JniFlags {
public:
    using CppType = ::MyFlags;
    using JniType = jobject;

    using Boxed = MyFlags;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<MyFlags>::get().flags(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<MyFlags>::get().create(jniEnv, static_cast<unsigned>(c), 3); }

private:
    MyFlags() : JniFlags("djinni/it/MyFlags") {}
    friend ::djinni::JniClass<MyFlags>;
};

}  // namespace djinni_generated
