// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from cpp_intefaces_as_lambdas.djinni

#include "interface_taking_lambda_convertible_callback.hpp"  // my header
#include "lambda_convertible_callback.hpp"

void InterfaceTakingLambdaConvertibleCallback::method_taking_lambda_convertible_callback (float valueToSet, std::function<void(bool)> callbackLambda)
{
    auto callback = std::make_shared<LambdaConvertibleCallbackLambdaAdapter>(callbackLambda);
    return method_taking_lambda_convertible_callback(valueToSet, callback);
}
void InterfaceTakingLambdaConvertibleCallback::second_method_taking_lambda_convertible_callback (int32_t valueToSet, std::function<void(bool)> callbackLambda)
{
    auto callback = std::make_shared<LambdaConvertibleCallbackLambdaAdapter>(callbackLambda);
    return second_method_taking_lambda_convertible_callback(valueToSet, callback);
}
