// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from all_datatypes.djinni

#import <Foundation/Foundation.h>

@interface ITAllDatatypes : NSObject
- (nonnull instancetype)initWithBooleanData:(BOOL)booleanData
                               integer8Data:(int8_t)integer8Data
                              integer16Data:(int16_t)integer16Data
                              integer32Data:(int32_t)integer32Data
                              integer64Data:(int64_t)integer64Data
                                float32Data:(float)float32Data
                                float64Data:(double)float64Data
                                 stringData:(nonnull NSString *)stringData
                                 binaryData:(nonnull NSData *)binaryData
                                   dateData:(nonnull NSDate *)dateData
                                   listData:(nonnull NSArray<NSNumber *> *)listData
                                    setData:(nonnull NSSet<NSNumber *> *)setData
                                    mapData:(nonnull NSDictionary<NSNumber *, NSNumber *> *)mapData
                               optionalData:(nullable NSNumber *)optionalData;
+ (nonnull instancetype)allDatatypesWithBooleanData:(BOOL)booleanData
                                       integer8Data:(int8_t)integer8Data
                                      integer16Data:(int16_t)integer16Data
                                      integer32Data:(int32_t)integer32Data
                                      integer64Data:(int64_t)integer64Data
                                        float32Data:(float)float32Data
                                        float64Data:(double)float64Data
                                         stringData:(nonnull NSString *)stringData
                                         binaryData:(nonnull NSData *)binaryData
                                           dateData:(nonnull NSDate *)dateData
                                           listData:(nonnull NSArray<NSNumber *> *)listData
                                            setData:(nonnull NSSet<NSNumber *> *)setData
                                            mapData:(nonnull NSDictionary<NSNumber *, NSNumber *> *)mapData
                                       optionalData:(nullable NSNumber *)optionalData;

@property (nonatomic, readonly) BOOL booleanData;

@property (nonatomic, readonly) int8_t integer8Data;

@property (nonatomic, readonly) int16_t integer16Data;

@property (nonatomic, readonly) int32_t integer32Data;

@property (nonatomic, readonly) int64_t integer64Data;

@property (nonatomic, readonly) float float32Data;

@property (nonatomic, readonly) double float64Data;

@property (nonatomic, readonly, nonnull) NSString * stringData;

@property (nonatomic, readonly, nonnull) NSData * binaryData;

@property (nonatomic, readonly, nonnull) NSDate * dateData;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * listData;

@property (nonatomic, readonly, nonnull) NSSet<NSNumber *> * setData;

@property (nonatomic, readonly, nonnull) NSDictionary<NSNumber *, NSNumber *> * mapData;

@property (nonatomic, readonly, nullable) NSNumber * optionalData;

@end
