// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, ITEnumData)
{
    ITEnumDataA,
    ITEnumDataB,
};
