// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_record.djinni

#import "ITMyRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto MyRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.id),
            ::djinni::String::toCpp(obj.info),
            ::djinni::Set<::djinni::String>::toCpp(obj.store),
            ::djinni::Map<::djinni::String, ::djinni::I32>::toCpp(obj.hash)};
}

auto MyRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[ITMyRecord alloc] initWithId:(::djinni::I32::fromCpp(cpp.id))
                                     info:(::djinni::String::fromCpp(cpp.info))
                                    store:(::djinni::Set<::djinni::String>::fromCpp(cpp.store))
                                     hash:(::djinni::Map<::djinni::String, ::djinni::I32>::fromCpp(cpp.hash))];
}

}  // namespace djinni_generated
