// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from all_datatypes.djinni

package djinni.it;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;

public final class AllDatatypes {


    /*package*/ final boolean booleanData;

    /*package*/ final byte integer8Data;

    /*package*/ final short integer16Data;

    /*package*/ final int integer32Data;

    /*package*/ final long integer64Data;

    /*package*/ final float float32Data;

    /*package*/ final double float64Data;

    /*package*/ final String stringData;

    /*package*/ final byte[] binaryData;

    /*package*/ final Date dateData;

    /*package*/ final ArrayList<Boolean> listData;

    /*package*/ final HashSet<Boolean> setData;

    /*package*/ final HashMap<Byte, Boolean> mapData;

    /*package*/ final Boolean optionalData;

    public AllDatatypes(
            boolean booleanData,
            byte integer8Data,
            short integer16Data,
            int integer32Data,
            long integer64Data,
            float float32Data,
            double float64Data,
            String stringData,
            byte[] binaryData,
            Date dateData,
            ArrayList<Boolean> listData,
            HashSet<Boolean> setData,
            HashMap<Byte, Boolean> mapData,
            Boolean optionalData) {
        this.booleanData = booleanData;
        this.integer8Data = integer8Data;
        this.integer16Data = integer16Data;
        this.integer32Data = integer32Data;
        this.integer64Data = integer64Data;
        this.float32Data = float32Data;
        this.float64Data = float64Data;
        this.stringData = stringData;
        this.binaryData = binaryData;
        this.dateData = dateData;
        this.listData = listData;
        this.setData = setData;
        this.mapData = mapData;
        this.optionalData = optionalData;
    }

    public boolean getBooleanData() {
        return booleanData;
    }

    public byte getInteger8Data() {
        return integer8Data;
    }

    public short getInteger16Data() {
        return integer16Data;
    }

    public int getInteger32Data() {
        return integer32Data;
    }

    public long getInteger64Data() {
        return integer64Data;
    }

    public float getFloat32Data() {
        return float32Data;
    }

    public double getFloat64Data() {
        return float64Data;
    }

    public String getStringData() {
        return stringData;
    }

    public byte[] getBinaryData() {
        return binaryData;
    }

    public Date getDateData() {
        return dateData;
    }

    public ArrayList<Boolean> getListData() {
        return listData;
    }

    public HashSet<Boolean> getSetData() {
        return setData;
    }

    public HashMap<Byte, Boolean> getMapData() {
        return mapData;
    }

    public Boolean getOptionalData() {
        return optionalData;
    }

    @Override
    public String toString() {
        return "AllDatatypes{" +
                "booleanData=" + booleanData +
                "," + "integer8Data=" + integer8Data +
                "," + "integer16Data=" + integer16Data +
                "," + "integer32Data=" + integer32Data +
                "," + "integer64Data=" + integer64Data +
                "," + "float32Data=" + float32Data +
                "," + "float64Data=" + float64Data +
                "," + "stringData=" + stringData +
                "," + "binaryData=" + binaryData +
                "," + "dateData=" + dateData +
                "," + "listData=" + listData +
                "," + "setData=" + setData +
                "," + "mapData=" + mapData +
                "," + "optionalData=" + optionalData +
        "}";
    }

}
