// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

#pragma once

#include <functional>

/** enum comment */
enum class MyEnum : int {
    /** enum option comment */
    OPTION1 = 0,
    OPTION2 = 1,
    OPTION3 = 2,
};

namespace std {

template <>
struct hash<::MyEnum> {
    size_t operator()(::MyEnum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
