// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_enum.djinni

package djinni.it;

/** enum comment */
public enum MyEnum {
    /** enum option comment */
    OPTION1,
    OPTION2,
    OPTION3,
    ;
}
