// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extern_generics.djinni

#include "my_record.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

MyRecord::MyRecord() = default;

MyRecord::~MyRecord() = default;

auto MyRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<MyRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::List<::djinni::String>::fromCpp(jniEnv, c.builtin)),
                                                           ::djinni::get(::djinni::List<::djinni::String>::fromCpp(jniEnv, c.external)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::List<::djinni::String>>::fromCpp(jniEnv, c.optional_builtin)),
                                                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::List<::djinni::String>>::fromCpp(jniEnv, c.optional_external)),
                                                           ::djinni::get(::djinni::List<::djinni::List<::djinni::String>>::fromCpp(jniEnv, c.list_of_list)),
                                                           ::djinni::get(::djinni::List<::djinni::List<::djinni::String>>::fromCpp(jniEnv, c.list_of_external)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto MyRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 7);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<MyRecord>::get();
    return {::djinni::List<::djinni::String>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_builtin)),
            ::djinni::List<::djinni::String>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_external)),
            ::djinni::Optional<std::optional, ::djinni::List<::djinni::String>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_optionalBuiltin)),
            ::djinni::Optional<std::optional, ::djinni::List<::djinni::String>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_optionalExternal)),
            ::djinni::List<::djinni::List<::djinni::String>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_listOfList)),
            ::djinni::List<::djinni::List<::djinni::String>>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_listOfExternal))};
}

}  // namespace djinni_generated
