// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_enum.djinni

#pragma once

#include <atomic>
#include <optional>
#include "../cpp-headers/my_enum.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "../cwrapper-headers/dh__my_enum.h"

#ifdef __cplusplus
}
#endif
int32_t int32_from_enum_my_enum(std::optional<::MyEnum> e);
int32_t int32_from_enum_my_enum(::MyEnum e);
std::optional<::MyEnum> get_boxed_enum_my_enum_from_int32(int32_t e);
