// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#import <Foundation/Foundation.h>

@interface ITCustomDatatype : NSObject
- (nonnull instancetype)initWithRecordData:(nonnull NSString *)recordData;
+ (nonnull instancetype)customDatatypeWithRecordData:(nonnull NSString *)recordData;

@property (nonatomic, readonly, nonnull) NSString * recordData;

@end
