// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#import "ITCustomDatatype.h"


@implementation ITCustomDatatype

- (nonnull instancetype)initWithRecordData:(nonnull NSString *)recordData
{
    if (self = [super init]) {
        _recordData = [recordData copy];
    }
    return self;
}

+ (nonnull instancetype)customDatatypeWithRecordData:(nonnull NSString *)recordData
{
    return [(ITCustomDatatype*)[self alloc] initWithRecordData:recordData];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p recordData:%@>", self.class, (void *)self, self.recordData];
}

@end
