// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_client_interface.djinni

#pragma once

#include <string>

class MyClientInterface {
public:
    virtual ~MyClientInterface() {}

    virtual bool log_string(const std::string & str) = 0;
};
