// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#pragma once

#include "custom_datatype.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class CustomDatatype final {
public:
    using CppType = ::CustomDatatype;
    using JniType = jobject;

    using Boxed = CustomDatatype;

    ~CustomDatatype();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    CustomDatatype();
    friend ::djinni::JniClass<CustomDatatype>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("djinni/it/CustomDatatype") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;)V") };
    const jfieldID field_recordData { ::djinni::jniGetFieldID(clazz.get(), "recordData", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
