// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from all_datatypes.djinni

#import "ITAllDatatypes.h"
#include "all_datatypes.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class ITAllDatatypes;

namespace djinni_generated {

struct AllDatatypes
{
    using CppType = ::AllDatatypes;
    using ObjcType = ITAllDatatypes*;

    using Boxed = AllDatatypes;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
