// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from requires.djinni

#pragma once

class RequiresEqInterface {
public:
    virtual ~RequiresEqInterface() {}

    virtual bool some_method() = 0;

    class Operators {
    public:
        static bool equals(const RequiresEqInterface& left, const RequiresEqInterface& right);
        static int32_t hash_code(const RequiresEqInterface& object);
    };
};
