// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from requires.djinni

#pragma once

class RequiresOrdInterface {
public:
    virtual ~RequiresOrdInterface() {}

    virtual bool some_method() = 0;

    class Operators {
    public:
        static int32_t compare(const RequiresOrdInterface& left, const RequiresOrdInterface& right);
    };
};
