// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from requires.djinni

#pragma once

class RequiresInterface {
public:
    virtual ~RequiresInterface() {}

    virtual bool some_method() = 0;

    class Operators {
    public:
        static bool equals(const RequiresInterface& left, const RequiresInterface& right);

        static int32_t hashCode(const RequiresInterface& object);
    };
};
