// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_client_interface.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdbool.h> // python_cdef_ignore

struct DjinniWrapperMyClientInterface;
void my_client_interface___wrapper_dec_ref(struct DjinniWrapperMyClientInterface * dh);
void my_client_interface___wrapper_add_ref(struct DjinniWrapperMyClientInterface * dh);
