// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "enum_data.hpp"

namespace djinni_generated {

class EnumData final : ::djinni::JniEnum {
public:
    using CppType = ::EnumData;
    using JniType = jobject;

    using Boxed = EnumData;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<EnumData>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<EnumData>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    EnumData() : JniEnum("djinni/it/EnumData") {}
    friend ::djinni::JniClass<EnumData>;
};

}  // namespace djinni_generated
