// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_client_interface.djinni

#pragma once

#include <atomic>
#include <optional>
#include "../cpp-headers/my_client_interface.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "../cwrapper-headers/cw__my_client_interface.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperMyClientInterface final {
    DjinniWrapperMyClientInterface(std::shared_ptr<::MyClientInterface>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::MyClientInterface> get(djinni::Handle<DjinniWrapperMyClientInterface> dw);
    static djinni::Handle<DjinniWrapperMyClientInterface> wrap(std::shared_ptr<::MyClientInterface> obj);

    const std::shared_ptr<::MyClientInterface> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
