// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_client_interface.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "my_client_interface.hpp"

#include "cw__my_client_interface.hpp"

std::shared_ptr<::MyClientInterface> DjinniWrapperMyClientInterface::get(djinni::WrapperRef<DjinniWrapperMyClientInterface> dw) {
    if (dw) {
        return dw->wrapped_obj;
    }
    return nullptr;
}

void my_client_interface___wrapper_add_ref(DjinniWrapperMyClientInterface * dh) {
    dh->ref_count.fetch_add(1);
}
void my_client_interface___wrapper_dec_ref(DjinniWrapperMyClientInterface * dh) {
    const size_t ref = dh->ref_count.fetch_sub(1);
    if (ref == 1) {// value before sub is returned
        delete dh;
    }
}
djinni::Handle<DjinniWrapperMyClientInterface> DjinniWrapperMyClientInterface::wrap(std::shared_ptr<::MyClientInterface> obj) {
    if (obj)
        return djinni::Handle<DjinniWrapperMyClientInterface>(new DjinniWrapperMyClientInterface{ std::move(obj) }, my_client_interface___wrapper_dec_ref);
    return nullptr;
}

