// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni

// bridging_header.h
// bridging_header

#import <Foundation/Foundation.h>

//! Project version number for bridgingheader.
FOUNDATION_EXPORT double bridgingheaderVersionNumber;

//! Project version string for bridgingheader.
FOUNDATION_EXPORT const unsigned char bridgingheaderVersionString[];

#import "ITCustomDatatype.h"
#import "ITOtherRecord.h"
