// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#import "ITCustomDatatype.h"
#import <Foundation/Foundation.h>

@interface ITOtherRecord : NSObject
- (nonnull instancetype)initWithCustomDatatypeData:(nonnull ITCustomDatatype *)customDatatypeData;
+ (nonnull instancetype)otherRecordWithCustomDatatypeData:(nonnull ITCustomDatatype *)customDatatypeData;

@property (nonatomic, readonly, nonnull) ITCustomDatatype * customDatatypeData;

@end
