// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from all_datatypes.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "all_datatypes.hpp"

#include "dh__all_datatypes.hpp"
#include "dh__list_bool.hpp"
#include "dh__map_int8_t_bool.hpp"
#include "dh__set_bool.hpp"
#include <chrono>
#include <optional>
#include <vector>

static void(*s_py_callback_set_bool___delete)(DjinniObjectHandle *);
void set_bool_add_callback___delete(void(* ptr)(DjinniObjectHandle *)) {
    s_py_callback_set_bool___delete = ptr;
}

void set_bool___delete(DjinniObjectHandle * drh) {
    s_py_callback_set_bool___delete(drh);
}
void optional_set_bool___delete(DjinniOptionalObjectHandle *  drh) {
    s_py_callback_set_bool___delete((DjinniObjectHandle *) drh);
}
static size_t ( * s_py_callback_set_bool__get_size)(DjinniObjectHandle *);

void set_bool_add_callback__get_size(size_t( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_set_bool__get_size = ptr;
}

static DjinniObjectHandle * ( * s_py_callback_set_bool__python_create)(void);

void set_bool_add_callback__python_create(DjinniObjectHandle *( * ptr)(void)) {
    s_py_callback_set_bool__python_create = ptr;
}

static void ( * s_py_callback_set_bool__python_add)(DjinniObjectHandle *, bool);

void set_bool_add_callback__python_add(void( * ptr)(DjinniObjectHandle *, bool)) {
    s_py_callback_set_bool__python_add = ptr;
}

static bool ( * s_py_callback_set_bool__python_next)(DjinniObjectHandle *);

void set_bool_add_callback__python_next(bool( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_set_bool__python_next = ptr;
}

djinni::Handle<DjinniObjectHandle> DjinniSetBool::fromCpp(const std::unordered_set<bool> & dc) {
    djinni::Handle<DjinniObjectHandle> _handle(s_py_callback_set_bool__python_create(), & set_bool___delete);
    for (const auto & it : dc) {
        s_py_callback_set_bool__python_add(_handle.get(), it);
    }

    return _handle;
}

std::unordered_set<bool> DjinniSetBool::toCpp(djinni::Handle<DjinniObjectHandle> dh) {
    std::unordered_set<bool>_ret;
    size_t size = s_py_callback_set_bool__get_size(dh.get());

    for (int i = 0; i < size; i++) {
        auto _el = s_py_callback_set_bool__python_next(dh.get());
        _ret.insert(std::move(_el));
    }

    return _ret;
}

djinni::Handle<DjinniOptionalObjectHandle> DjinniSetBool::fromCpp(std::optional<std::unordered_set<bool>> dc) {
    if (dc == std::experimental::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(DjinniSetBool::fromCpp(std::move(* dc)), optional_set_bool___delete);
}

std::optional<std::unordered_set<bool>>DjinniSetBool::toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh) {
     if (dh) {
        return std::optional<std::unordered_set<bool>>(DjinniSetBool::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), set_bool___delete)));
    }
    return std::experimental::nullopt;
}

