// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from all_datatypes.djinni

#pragma once

#include <atomic>
#include <optional>
#include "all_datatypes.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__map_int8_t_bool.h"

#ifdef __cplusplus
}
#endif
struct DjinniMapInt8TBool {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::unordered_map<int8_t, bool> & dc);
    static std::unordered_map<int8_t, bool> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::optional<std::unordered_map<int8_t, bool>> dc);
    static std::optional<std::unordered_map<int8_t, bool>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
