// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once

#include <atomic>
#include <optional>
#include "../cpp-headers/enum_data.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "../cwrapper-headers/dh__enum_data.h"

#ifdef __cplusplus
}
#endif
int32_t int32_from_enum_enum_data(std::optional<::EnumData> e);
int32_t int32_from_enum_enum_data(::EnumData e);
std::optional<::EnumData> get_boxed_enum_enum_data_from_int32(int32_t e);
