// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from all_datatypes.djinni

#pragma once

#include <atomic>
#include <optional>
#include "../cpp-headers/all_datatypes.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "../cwrapper-headers/dh__all_datatypes.h"

#ifdef __cplusplus
}
#endif
struct DjinniAllDatatypes {
    static djinni::Handle<DjinniRecordHandle> fromCpp(const ::AllDatatypes& dr);
    static ::AllDatatypes toCpp(djinni::Handle<DjinniRecordHandle> dh);
    static djinni::Handle<DjinniOptionalRecordHandle> fromCpp(std::optional<::AllDatatypes> dc);
    static std::optional<::AllDatatypes> toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh);
};
