// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#include <iostream> // for debugging
#include <cassert>
#include "djinni/cwrapper/wrapper_marshal.hpp"
#include "../cpp-headers/enum_data.hpp"

int32_t int32_from_enum_enum_data(std::optional<::EnumData> e) {
    if (e) {
        return static_cast<int32_t>(* e);
    }
    return -1; // -1 to signal null boxed enum
}

int32_t int32_from_enum_enum_data(::EnumData e) {
    return static_cast<int32_t>(e);
}
std::optional<::EnumData> get_boxed_enum_enum_data_from_int32(int32_t e) {
    if (e == -1) { // to signal null enum
        return {};
    }
    return std::optional<::EnumData>(static_cast<::EnumData>(e));
}
