// AUTOGENERATED FILE - DO NOT MODIFY!
// The file included here provides default JNI_OnLoad and JNI_OnUnload implementations.
// Disable the generation of this file with `--jni-generate-main=false`.
#include "djinni/jni/djinni_jni_main.hpp"
