// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_client_interface.djinni

#pragma once

#include "djinni_support.hpp"
#include "my_client_interface.hpp"

namespace djinni_generated {

class MyClientInterface final : ::djinni::JniInterface<::MyClientInterface, MyClientInterface> {
public:
    using CppType = std::shared_ptr<::MyClientInterface>;
    using CppOptType = std::shared_ptr<::MyClientInterface>;
    using JniType = jobject;

    using Boxed = MyClientInterface;

    ~MyClientInterface();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<MyClientInterface>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<MyClientInterface>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    MyClientInterface();
    friend ::djinni::JniClass<MyClientInterface>;
    friend ::djinni::JniInterface<::MyClientInterface, MyClientInterface>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::MyClientInterface
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        bool log_string(const std::string & str) override;

    private:
        friend ::djinni::JniInterface<::MyClientInterface, ::djinni_generated::MyClientInterface>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("djinni/it/MyClientInterface") };
    const jmethodID method_logString { ::djinni::jniGetMethodID(clazz.get(), "logString", "(Ljava/lang/String;)Z") };
};

}  // namespace djinni_generated
