// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_flags.djinni

#pragma once

#include "../cpp-headers/my_flags.hpp"

/** flag comment */
[System::Flags]
public enum class MyFlags {
    NoFlags = 0,
    /** flag option comment */
    Flag1 = 1u << 0,
    Flag2 = 1u << 1,
    Flag3 = 1u << 2,
    AllFlags = 0 | Flag1 | Flag2 | Flag3,
};
