// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_flags.djinni

#include "MyFlags.hpp"  // my header
#include "../cpp-headers/my_flags.hpp"

// Empty... making sure the symbols get included in the build.
