// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_flags.djinni

#include "MyFlags.hpp"  // my header
#include "my_flags.hpp"

// Empty... making sure the symbols get included in the build.
