// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_flags.djinni

#pragma once

#include "my_flags.hpp"

[System::Flags]
public enum class MyFlags {
    NoFlags = 0,
    Flag1 = 1 << 0,
    Flag2 = 1 << 1,
    Flag3 = 1 << 2,
    AllFlags = 0 | Flag1 | Flag2 | Flag3,
};
