// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#pragma once

#include <atomic>
#include <optional>
#include "../cpp-headers/custom_datatype.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "../cwrapper-headers/dh__custom_datatype.h"

#ifdef __cplusplus
}
#endif
struct DjinniCustomDatatype {
    static djinni::Handle<DjinniRecordHandle> fromCpp(const ::CustomDatatype& dr);
    static ::CustomDatatype toCpp(djinni::Handle<DjinniRecordHandle> dh);
    static djinni::Handle<DjinniOptionalRecordHandle> fromCpp(std::optional<::CustomDatatype> dc);
    static std::optional<::CustomDatatype> toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh);
};
