// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

#pragma once

#include <atomic>
#include <optional>
#include "other_record.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__other_record.h"

#ifdef __cplusplus
}
#endif
struct DjinniOtherRecord {
    static djinni::Handle<DjinniRecordHandle> fromCpp(const ::OtherRecord& dr);
    static ::OtherRecord toCpp(djinni::Handle<DjinniRecordHandle> dh);
    static djinni::Handle<DjinniOptionalRecordHandle> fromCpp(std::optional<::OtherRecord> dc);
    static std::optional<::OtherRecord> toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh);
};
