// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_enum.djinni

#pragma once

#include "djinni_support.hpp"
#include "my_enum.hpp"

namespace djinni_generated {

class MyEnum final : ::djinni::JniEnum {
public:
    using CppType = ::MyEnum;
    using JniType = jobject;

    using Boxed = MyEnum;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<MyEnum>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<MyEnum>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    MyEnum() : JniEnum("djinni/it/MyEnum") {}
    friend ::djinni::JniClass<MyEnum>;
};

}  // namespace djinni_generated
