// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from cppcli_interface_nonnull.djinni

#pragma once

#include "../cpp-headers/my_cpp_interface.hpp"
#include "nn.hpp"
#include <memory>

/** interface comment */
public ref class MyCppInterface abstract {
public:
    /** method comment */
    virtual void MethodReturningNothing(int value) abstract;

    virtual int MethodReturningSomeType(System::String^ key) abstract;

    virtual int MethodChangingNothing() abstract;

    static int GetVersion();

internal:
    using CppType = dropbox::oxygen::nn_shared_ptr<::MyCppInterface>;
    using CppOptType = std::shared_ptr<::MyCppInterface>;
    using CsType = MyCppInterface^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};
