// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_client_interface.djinni

#include "my_client_interface.hpp"  // my header

namespace djinni_generated {


EMSCRIPTEN_BINDINGS(_my_client_interface) {
    em::class_<::MyClientInterface>("MyClientInterface")
        .smart_ptr<std::shared_ptr<::MyClientInterface>>("MyClientInterface")
        .function("nativeDestroy", &MyClientInterface::nativeDestroy)
        ;
}

}  // namespace djinni_generated
