// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_client_interface.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "my_client_interface.hpp"

namespace djinni_generated {

struct MyClientInterface : ::djinni::JsInterface<::MyClientInterface, MyClientInterface> {
    using CppType = std::shared_ptr<::MyClientInterface>;
    using CppOptType = std::shared_ptr<::MyClientInterface>;
    using JsType = em::val;
    using Boxed = MyClientInterface;

    static CppType toCpp(JsType j) { return _fromJs(j); }
    static JsType fromCppOpt(const CppOptType& c) { return {_toJs(c)}; }
    static JsType fromCpp(const CppType& c) {
        ::djinni::checkForNull(c.get(), "MyClientInterface::fromCpp");
        return fromCppOpt(c);
    }


};

}  // namespace djinni_generated
