// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extern_generics.djinni

#import <Foundation/Foundation.h>

/** record comment */
@interface ITMyRecord : NSObject
- (nonnull instancetype)initWithBuiltin:(nonnull NSArray<NSString *> *)builtin
                               external:(nonnull NSArray<NSString *> *)external;
+ (nonnull instancetype)myRecordWithBuiltin:(nonnull NSArray<NSString *> *)builtin
                                   external:(nonnull NSArray<NSString *> *)external;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * builtin;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * external;

@end
