// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_record.djinni

package djinni.it;

import java.util.HashMap;
import java.util.HashSet;

/** record comment */
public final class MyRecord {

    public static final String STRING_CONST = "Constants can be put here";


    /*package*/ final int id;

    /*package*/ final String info;

    /*package*/ final HashSet<String> store;

    /*package*/ final HashMap<String, Integer> hash;

    /*package*/ final MyEnum myEnum;

    public MyRecord(
            int id,
            String info,
            HashSet<String> store,
            HashMap<String, Integer> hash,
            MyEnum myEnum) {
        this.id = id;
        this.info = info;
        this.store = store;
        this.hash = hash;
        this.myEnum = myEnum;
    }

    /** record property comment */
    public int getId() {
        return id;
    }

    public String getInfo() {
        return info;
    }

    public HashSet<String> getStore() {
        return store;
    }

    public HashMap<String, Integer> getHash() {
        return hash;
    }

    public MyEnum getMyEnum() {
        return myEnum;
    }

    @Override
    public String toString() {
        return "MyRecord{" +
                "id=" + id +
                "," + "info=" + info +
                "," + "store=" + store +
                "," + "hash=" + hash +
                "," + "myEnum=" + myEnum +
        "}";
    }

}
