// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdbool.h> // python_cdef_ignore
#include <stdint.h> // python_cdef_ignore

void set_bool___delete(struct DjinniObjectHandle *);
void optional_set_bool___delete(struct DjinniOptionalObjectHandle *);
void set_bool_add_callback___delete(void(* ptr)(struct DjinniObjectHandle * ));
void set_bool_add_callback__get_size(size_t( * ptr)(struct DjinniObjectHandle *));
void set_bool_add_callback__create(struct DjinniObjectHandle *( * ptr)(void));
void set_bool_add_callback__add(void( * ptr)(struct DjinniObjectHandle *, bool));
void set_bool_add_callback__next(bool( * ptr)(struct DjinniObjectHandle *));
