// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdbool.h> // python_cdef_ignore
#include <stdint.h> // python_cdef_ignore

void map_int8_t_bool___delete(struct DjinniObjectHandle *);
void optional_map_int8_t_bool___delete(struct DjinniOptionalObjectHandle *);
void map_int8_t_bool_add_callback___delete(void(* ptr)(struct DjinniObjectHandle * ));
void map_int8_t_bool_add_callback__get_value(bool( * ptr)(struct DjinniObjectHandle *, int8_t));
void map_int8_t_bool_add_callback__get_size(size_t( * ptr)(struct DjinniObjectHandle *));
void map_int8_t_bool_add_callback__create(struct DjinniObjectHandle *( * ptr)(void));
void map_int8_t_bool_add_callback__add(void( * ptr)(struct DjinniObjectHandle *, int8_t, bool));
void map_int8_t_bool_add_callback__next(int8_t( * ptr)(struct DjinniObjectHandle *));
