// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from all_datatypes.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdbool.h> // python_cdef_ignore
#include <stdint.h> // python_cdef_ignore

struct DjinniAllDatatypes;
void all_datatypes___delete(struct DjinniRecordHandle * );
void optional_all_datatypes___delete(struct DjinniOptionalRecordHandle * );
void all_datatypes_add_callback_get_all_datatypes_f1(bool( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f2(int8_t( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f3(int16_t( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f4(int32_t( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f5(int64_t( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f6(float( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f7(double( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f8(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f9(struct DjinniBinary *( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f10(uint64_t( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f11(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f12(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f13(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_get_all_datatypes_f14(struct DjinniBoxedBool *( * ptr)(struct DjinniRecordHandle *));
void all_datatypes_add_callback_python_create_all_datatypes(struct DjinniRecordHandle *( * ptr)(bool, int8_t, int16_t, int32_t, int64_t, float, double, struct DjinniString *, struct DjinniBinary *, uint64_t, struct DjinniObjectHandle *, struct DjinniObjectHandle *, struct DjinniObjectHandle *, struct DjinniBoxedBool *));
void all_datatypes_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
