// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_client_interface.djinni

package djinni.it;

public abstract class MyClientInterface {
    public abstract boolean logString(String str);
}
