// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_flags.djinni


/** flag comment */
export enum MyFlags {
    NO_FLAGS = 0,
    /** flag option comment */
    FLAG1 = 1 << 0,
    FLAG2 = 1 << 1,
    FLAG3 = 1 << 2,
    ALL_FLAGS = 0 | (1 << 0) | (1 << 1) | (1 << 2),
}

export interface Module_statics {
}
