# AUTOGENERATED FILE - DO NOT MODIFY!
# This file was generated by Djinni from my_record.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyObject, CPyObjectProxy, CPyPrimitive, CPyRecord, CPyString

from dh__map_string_int32_t import MapStringInt32THelper
from dh__map_string_int32_t import MapStringInt32TProxy
from dh__set_string import SetStringHelper
from dh__set_string import SetStringProxy
from _cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class MyRecord:
    """
     record comment
    Fields
        id: record property comment
        info
        store
        hash
    """

    c_data_set = MultiSet()

    @staticmethod
    def check_c_data_set_empty():
        assert len(MyRecord.c_data_set) == 0
        SetStringHelper.check_c_data_set_empty()
        MapStringInt32THelper.check_c_data_set_empty()

    STRING_CONST = "Constants can be put here"


    def __init__(self, id, info, store, hash):
        self.id = id
        self.info = info
        self.store = store
        self.hash = hash


