// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_cpp_interface.djinni

#import <Foundation/Foundation.h>

/** Interfaces can also have constants */
extern int32_t const ITMyCppInterfaceVersion;

@interface ITMyCppInterface : NSObject

- (void)methodReturningNothing:(int32_t)value;

- (int32_t)methodReturningSomeType:(nonnull NSString *)key;

+ (int32_t)getVersion;

@end
