// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni

#pragma once

#include "../cpp-headers/custom_datatype.hpp"
#include "djinni/wasm/djinni_wasm.hpp"

namespace djinni_generated {

struct CustomDatatype
{
    using CppType = ::CustomDatatype;
    using JsType = em::val;
    using Boxed = CustomDatatype;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
