// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni

#include "custom_datatype.hpp"  // my header

namespace djinni_generated {

auto CustomDatatype::toCpp(const JsType& j) -> CppType {
    return {::djinni::String::Boxed::toCpp(j["recordData"])};
}
auto CustomDatatype::fromCpp(const CppType& c) -> JsType {
    em::val js = em::val::object();
    js.set("recordData", ::djinni::String::Boxed::fromCpp(c.recordData));
    return js;
}

}  // namespace djinni_generated
