// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from using_custom_datatypes.djinni

#pragma once

#include "djinni_wasm.hpp"
#include "other_record.hpp"

namespace djinni_generated {

struct OtherRecord
{
    using CppType = ::OtherRecord;
    using JsType = em::val;
    using Boxed = OtherRecord;

    static CppType toCpp(const JsType& j);
    static JsType fromCpp(const CppType& c);
};

}  // namespace djinni_generated
