// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_flags.djinni

#import <Foundation/Foundation.h>

/** flag comment */
typedef NS_OPTIONS(NSUInteger, ITMyFlags)
{
    ITMyFlagsNoFlags = 0,
    /** flag option comment */
    ITMyFlagsFlag1 = 1 << 0,
    ITMyFlagsFlag2 = 1 << 1,
    ITMyFlagsFlag3 = 1 << 2,
    ITMyFlagsAllFlags = 0 | (1 << 0) | (1 << 1) | (1 << 2),
};
