// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni

package djinni.it;

/**
 * enum comment
 *
 * @deprecated Use something else
 */
@Deprecated
public enum MyEnum {
    /** @deprecated Use something else */
    @Deprecated
    OPTION1,
    /** not deprecated */
    OPTION2,
    ;
}
