// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni

package djinni.it;

/**
 * flags comment
 *
 * @deprecated Use someother flags
 */
@Deprecated
public enum MyFlags {
    /** @deprecated Use someother flag */
    @Deprecated
    FLAG1,
    /** not deprecated */
    FLAG2,
    ;
}
