// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from deprecation.djinni

package djinni.it;

/**
 * record comment
 *
 * @deprecated Use someother record
 */
@Deprecated
public final class MyRecord {

    /** @deprecated Use someother constant */
    @Deprecated
    public static final int VERSION = 1;


    /*package*/ final String attribute;

    /*package*/ final String another;

    /*package*/ final String again;

    public MyRecord(
            String attribute,
            String another,
            String again) {
        this.attribute = attribute;
        this.another = another;
        this.again = again;
    }

    /** @deprecated Use someother attribute */
    @Deprecated
    public String getAttribute() {
        return attribute;
    }

    /** not deprecated */
    public String getAnother() {
        return another;
    }

    /** @deprecated Use someother attribute */
    @Deprecated
    public String getAgain() {
        return again;
    }

    @Override
    public String toString() {
        return "MyRecord{" +
                "attribute=" + attribute +
                "," + "another=" + another +
                "," + "again=" + again +
        "}";
    }

}
