name: CI
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
          key: scala-build-deps
      - name: Building
        run: sbt assembly
      - uses: actions/upload-artifact@v2
        with:
          name: djinni-generator
          path: target/bin/djinni
  it:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
          key: scala-build-deps
      - uses: actions/download-artifact@v2
        with:
          name: djinni-generator
          path: target/bin
      - name: Restoring file permissions of artifact
        run: chmod u+x target/bin/djinni
      - name: Running integration-tests
        run: sbt it:test
