on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Caching dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2
          key: scala-build-deps
      - name: Building
        run: sbt assembly
      - name: creating bat
        run: cp target/bin/djinni target/bin/djinni.bat
      - name: get upload-url for latest release
        run:  |
              upload_url=$(curl -sL https://api.github.com/repos/actions/checkout/releases/latest | jq -r '.upload_url')
              echo ::set-env name=UPLOAD_URL::$upload_url
        shell: bash
      - name: Upload Release Asset for macOS/Linux
        id: upload-release-asset-unix
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: target/bin/djinni
          asset_name: djinni
      - name: Upload Release Asset for Windows
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: target/bin/djinni.bat
          asset_name: djinni.bat
