// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

package djinni.it;

public final class CustomDatatype {


    /*package*/ final String recordData;

    public CustomDatatype(
            String recordData) {
        this.recordData = recordData;
    }

    public String getRecordData() {
        return recordData;
    }

    @Override
    public String toString() {
        return "CustomDatatype{" +
                "recordData=" + recordData +
        "}";
    }

}
