// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from using_custom_datatypes.djinni

package djinni.it;

public final class OtherRecord {


    /*package*/ final CustomDatatype customDatatypeData;

    public OtherRecord(
            CustomDatatype customDatatypeData) {
        this.customDatatypeData = customDatatypeData;
    }

    public CustomDatatype getCustomDatatypeData() {
        return customDatatypeData;
    }

    @Override
    public String toString() {
        return "OtherRecord{" +
                "customDatatypeData=" + customDatatypeData +
        "}";
    }

}
