// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from extern_generics.djinni

package djinni.it;

import java.util.ArrayList;

/** record comment */
public final class MyRecord {


    /*package*/ final ArrayList<String> builtin;

    /*package*/ final java.util.ArrayList<String> external;

    /*package*/ final ArrayList<String> optionalBuiltin;

    /*package*/ final java.util.ArrayList<String> optionalExternal;

    /*package*/ final ArrayList<ArrayList<String>> listOfList;

    /*package*/ final ArrayList<java.util.ArrayList<String>> listOfExternal;

    public MyRecord(
            ArrayList<String> builtin,
            java.util.ArrayList<String> external,
            ArrayList<String> optionalBuiltin,
            java.util.ArrayList<String> optionalExternal,
            ArrayList<ArrayList<String>> listOfList,
            ArrayList<java.util.ArrayList<String>> listOfExternal) {
        this.builtin = builtin;
        this.external = external;
        this.optionalBuiltin = optionalBuiltin;
        this.optionalExternal = optionalExternal;
        this.listOfList = listOfList;
        this.listOfExternal = listOfExternal;
    }

    public ArrayList<String> getBuiltin() {
        return builtin;
    }

    public java.util.ArrayList<String> getExternal() {
        return external;
    }

    public ArrayList<String> getOptionalBuiltin() {
        return optionalBuiltin;
    }

    public java.util.ArrayList<String> getOptionalExternal() {
        return optionalExternal;
    }

    public ArrayList<ArrayList<String>> getListOfList() {
        return listOfList;
    }

    public ArrayList<java.util.ArrayList<String>> getListOfExternal() {
        return listOfExternal;
    }

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof MyRecord)) {
            return false;
        }
        MyRecord other = (MyRecord) obj;
        return this.builtin.equals(other.builtin) &&
                this.external.equals(other.external) &&
                ((this.optionalBuiltin == null && other.optionalBuiltin == null) || (this.optionalBuiltin != null && this.optionalBuiltin.equals(other.optionalBuiltin))) &&
                ((this.optionalExternal == null && other.optionalExternal == null) || (this.optionalExternal != null && this.optionalExternal.equals(other.optionalExternal))) &&
                this.listOfList.equals(other.listOfList) &&
                this.listOfExternal.equals(other.listOfExternal);
    }

    @Override
    public int hashCode() {
        // Pick an arbitrary non-zero starting value
        int hashCode = 17;
        hashCode = hashCode * 31 + builtin.hashCode();
        hashCode = hashCode * 31 + (external.hashCode());
        hashCode = hashCode * 31 + (optionalBuiltin == null ? 0 : optionalBuiltin.hashCode());
        hashCode = hashCode * 31 + (optionalExternal == null ? 0 : optionalExternal.hashCode());
        hashCode = hashCode * 31 + listOfList.hashCode();
        hashCode = hashCode * 31 + listOfExternal.hashCode();
        return hashCode;
    }

    @Override
    public String toString() {
        return "MyRecord{" +
                "builtin=" + builtin +
                "," + "external=" + external +
                "," + "optionalBuiltin=" + optionalBuiltin +
                "," + "optionalExternal=" + optionalExternal +
                "," + "listOfList=" + listOfList +
                "," + "listOfExternal=" + listOfExternal +
        "}";
    }

}
