// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_flags.djinni

package djinni.it;

/** flag comment */
public enum MyFlags {
    /** flag option comment */
    FLAG1,
    FLAG2,
    FLAG3,
    ;
}
