// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from my_client_interface.djinni

#pragma once

#include "my_client_interface.hpp"
#include <memory>

public ref class MyClientInterface abstract {
public:
    virtual bool LogString(System::String^ str) abstract;

internal:
    using CppType = std::shared_ptr<::MyClientInterface>;
    using CppOptType = std::shared_ptr<::MyClientInterface>;
    using CsType = MyClientInterface^;

    static CppType ToCpp(CsType cs);
    static CsType FromCppOpt(const CppOptType& cpp);
    static CsType FromCpp(const CppType& cpp) { return FromCppOpt(cpp); }
};
