// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from my_client_interface.djinni

#include "MyClientInterface.hpp"  // my header
#include "djinni/cppcli/Error.hpp"
#include "djinni/cppcli/Marshal.hpp"
#include "djinni/cppcli/WrapperCache.hpp"

class MyClientInterfaceCsProxy : public ::MyClientInterface {
    using CsType = ::MyClientInterface^;
    using CsRefType = ::djinni::CsRef<CsType>;
    using HandleType = ::djinni::CsProxyCache::Handle<::djinni::CsRef<CsType>>;
public:
    MyClientInterfaceCsProxy(CsRefType cs) : m_djinni_private_proxy_handle(std::move(cs)) {}
    MyClientInterfaceCsProxy(const ::djinni::CsRef<System::Object^>& ptr) : MyClientInterfaceCsProxy(CsRefType(dynamic_cast<CsType>(ptr.get()))) {}

    bool log_string(const std::string & str) override
    {
        auto cs_result = djinni_private_get_proxied_cs_object()->LogString(::djinni::String::FromCpp(str));
        // TODO check cs_result for null
        return ::djinni::Bool::ToCpp(cs_result);
    }

    CsType djinni_private_get_proxied_cs_object() {
        return m_djinni_private_proxy_handle.get().get();
    }

private:
    HandleType m_djinni_private_proxy_handle;
};

MyClientInterface::CppType MyClientInterface::ToCpp(MyClientInterface::CsType cs)
{
    if (!cs) {
        return nullptr;
    }
    return ::djinni::get_cs_proxy<MyClientInterfaceCsProxy>(cs);
}

MyClientInterface::CsType MyClientInterface::FromCppOpt(const MyClientInterface::CppOptType& cpp)
{
    if (!cpp) {
        return nullptr;
    }
    return dynamic_cast<MyClientInterfaceCsProxy*>(cpp.get())->djinni_private_get_proxied_cs_object();
}
